### DISCUSSION TITLE
GitHub runners not picking up jobs?

### DISCUSSION THREAD

**Discussion by megastep** [ubicloud/ubicloud#3192] [Q&A] [answered]
Hi all,

I've been using Ubicloud on an open-source project to run CI tests on some specific Linux distributions. I've noticed that lately, the jobs sent to Ubicloud never get processed. There is no details available besides "Runner doesn't have a job yet" in the Ubicloud console, and GitHub states that the job is waiting to be picked up.

Is there something I'm doing wrong here? The workflow looks like this:

```
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            container: 'ubuntu:latest'
            artifact: 'ubuntu'

          - os: ubicloud-standard-2
            container: 'alpine:latest'
            artifact: 'alpine'
            
          - os: ubicloud-standard-2
            container: 'rockylinux:9'
            artifact: 'rockylinux'
            
          - os: windows-latest
            artifact: 'windows'

          - os: macos-latest
            artifact: 'macOS'
```

Full reference: https://github.com/megastep/makeself/blob/master/.github/workflows/build.yml
