### ISSUE TITLE
Post Setup JDK 17 doesn't finish

### ISSUE THREAD

**Issue by TillJohanndeiter** [ubicloud/ubicloud#2988]
If if setup jdk 17 like this
```

      - name: Setup JDK 17
        uses: ubicloud/setup-java@v4
        with:
          distribution: adopt
          java-version: 17
          cache: 'gradle'
```

then the Post JDK 17 step needs sometimes more than 3m.

```
Post job cleanup.
/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/yast/yast --files-from manifest.txt --use-compress-program zstdmt
Cache Size: ~[2](https://github.com/TillJohanndeiter/yast/actions/runs/13872699361/job/38821279607#step:28:2)171 MB (2276531961 B)
Cache saved successfully
Cache saved with the key: setup-java-Linux-x64-gradle-abbe9b5f8fd76040d5671f1e641a3dbad9ab2807f363e674206[3](https://github.com/TillJohanndeiter/yast/actions/runs/13872699361/job/38821279607#step:28:3)0616bc195225

```
